import Component from '@glimmer/component';

export const defaultTitles = {
  search: 'icon-search',
  'icon-calendar': 'icon-calendar',
  chevron: 'Path 2 Copy 28',
  'sort-descending': 'icon-sort-descending',
  alert: 'icon-alert',
  'icon-info': 'Icon Info',
  gihub: 'GitHub',
  'select-arrows': 'Arrows',
  'icon-click': 'icon_click copy 2',
  'role-admin': 'icon-admin',
  'addon-docs-pen': 'Group 2 Copy 2',
  'text-icon': 'icon-text-layer',
  'role-viewer': 'icon-viewer',
  'mobile_inbox-channel-icon': 'Icon/Mobile Inbox',
  'down-arrow': 'icon-dropdown-arrow',
  nested: 'Icon-Nested',
  'dynamic-icon': 'dynamic content icon',
  'role-operator': 'icon-operator',
  'icon-trash': 'icon-trash',
  cursor: 'icon-cursor',
  'web-channel-icon': 'Icon/Web',
  'image-icon': 'icon-image-layer',
  check: 'icon-success-check',
  'email-builder-icon': 'Icon/Builder',
  'app-channel-icon': 'Icon/In-App',
  refresh: 'icon-refresh',
  feedback: 'Feedback Icon',
  'email-html-icon': 'Icon/HTML',
  failure: 'icon-failure',
  'icon-help': 'icon-help',
  'email-block-icon': 'Icon/Block',
  success: 'icon-success',
  'ads-channel-icon': 'Icon/Display',
  'fallback-icon': 'fallback content icon',
  sort: 'icon-sort',
  'role-analyst': 'icon-analyst',
  'role-editor': 'icon-editor',
  'role-manager': 'icon-manager',
  switch: 'icon-switch',
  calendar: 'Calendar icon',
  'push-channel-icon': 'Icon/Push',
  weather: 'Icon / Weather / Color',
  'map-helper': 'Icon / Map Helper / Color',
  'social-chatter': 'Icon / Social Chatter / Color',
  olapic: 'Icon / Olapic / Color',
  'ads-icon': 'svg-channel--dislpay',
  'custom-app': 'Icon / Custom App Two / Color',
  'bar-chart': 'Icon / Bar Chart / Color',
  'dynamic-timer': 'Icon / Dynamic Timer / Color',
  instagram: 'Icon / Instagram / Color',
  cart: 'Icon / Custom App Three / Color',
  'mobile_inbox-icon': 'svg-channel-mobile-inbox',
  'email-icon': 'svg-channel-email',
  'image-personalization': 'Icon / Image Personalization / Color',
  'barcode-generator': 'Icon / Barcode Generator / Color',
  'local-maps': 'Icon / Local Maps / Color',
  'push-icon': 'svg-channel--mobile-push',
  spanner: 'Icon / Custom App One / Color',
  'augmented-reality': 'Icon / Augmented Reality / Color',
  'qr-code-generator': 'Icon / QR Code Generator / Color',
  facebook: 'icon-facebook',
  polling: 'Icon / Polling / Color',
  'multi-personalization': 'Icon / Multi Personalization / Color',
  pinterest: 'icon-pinterest',
  'rss-feed': 'Icon / RSS Feed / Color',
  'static-pic': 'Icon / StaticPic / Color',
  'local-time': 'Icon / Local Time / Color',
  'countdown-timer': 'Icon / Countdown Timer / Color',
  'web-icon': 'svg-channel--web',
  video: 'Icon / Video / Color',
  'proximity-targeting': 'Icon / Proximity Targeting / Color',
  twitter: 'Icon / Twitter / Color',
  'app-icon': 'svg-channel-in-app',
  'media-library': 'Icon / Media Library / Color',
  'social-sharing': 'Icon / Sharing Sharing / Color',
  'web-crop': 'Icon / Webcrop / Color',
  'sort-ascending': 'icon-sort-ascending',
  locked: 'icon-locked',
  'icon-dropdown-arrow': 'icon-dropdown-arrow',
  'role-developer': 'icon-developer',
  'email-channel-icon': 'Icon/Email Alt',
  'link-icon': 'icon-link',
};

export default class FluidIcon extends Component {
  get title() {
    return defaultTitles[this.args.name];
  }
}
